<?php
    $this->redirectLinks = false;

    $title = "";
    foreach ($this->headTitle() as $item) {
        $title .= $item;
    }

    echo '<h1>' . $title . '</h1>' . PHP_EOL;

    print '<p class="center success">';

    $href = $this->addParamToUrl('login', 'redirect', 'account');

    print $this->translate('Your new password is now <strong>%s</strong>. You can %s with this new password. Don\'t forget to change it again to a personal password as soon as possible.',
            $this->escape($this->newpwd),
            $this->anchor($href, $this->translate('log in'))
            );
    print '</p>';
?>
