<noscript>
    <style type="text/css">
        #map, #message, #data_controls, #login_controls, #user_area, #login_area, #newpwd_area {
            display: none;
        }
    </style>

    <p><?php echo $this->translate('SYJ needs javascript. Please activate scripts in your browser.');?></p>
</noscript>

<div id="map"></div>

<div id="message" class="message info">
<?php if (!$this->path and !$this->loggedUser) {?>
<?php echo $this->translate('Welcome on Syj.')?>
<br/>
<?php echo $this->translate('To create a journey, just click on the map to add points to your route. You can zoom and move map with controls upper left.')?>
<br/>
<?php echo $this->translate('When you have finished a path, press "save", button.')?>
<?php }?>
</div>


<div id="path-length" class="menu-group">
    <div id="path-length-title" class="info-title"><?php echo $this->translate('route length')?></div>
    <div id="path-length-content">
    </div>
</div>

<div id="menu">

    <?php echo $this->localeSwitcher(); ?>

    <div id="login_controls" class="menu-group">
        <div>
            <div class="menu-item">
            <?php
                echo $this->anchor('login', $this->translate('login'), array('id' => 'login_control_anchor'));
                $anchortext = sprintf("<span id=\"account-create-anchor\">%s</span><span id=\"account-info\"><br>%s</span>",
                                      $this->translate('create an account'),
                                      $this->translate('Whith an account, you can manage and modify your routes'));
                ?>
               </div>
               <div class="menu-item">
               <?php
                echo $this->anchor('', $anchortext, array('id' => 'user_control_anchor'), false);
            ?>
            </div>
        </div>
        <div>
            <?php echo $this->logoutLink(); ?>
        </div>
    </div>

    <?php if (isset($this->path)) { ?>
        <div id="path-infos" class="menu-group">
            <div class="menu-item">
                <div id="path-infos-toggler"><a href="" id="path-infos-anchor"><?php echo $this->translate("route infos")?></a></div>
             </div>
                <div id="path-infos-content" class="menu-item">

                    <div id="path-directlink-title" class="info-title"><?php echo $this->translate("direct link")?></div>
                    <div id="path-directlink-content"><?php
                            $serverUrl = rtrim($this->serverUrl(), '/');
                            $baseUrl = trim($this->baseUrl(), '/');
                            $fullBaseUrl = $serverUrl . '/' . ($baseUrl ? ($baseUrl . '/'): '');
                            $urlcomp = urlencode($this->path->urlcomp ?: $this->path->id);
                            $href = $fullBaseUrl . 'idx/' . $urlcomp . '?format=raw';
                            printf('<a href="%s" title="%s">%s</a>',
                                        $href,
                                        $this->translate('direct link'),
                                        $this->escape($href));
                        ?></div>

                    <div id="path-export-title" class="info-title"><?php echo $this->translate("export")?></div>
                    <div id="path-export-content"><?php
                       $href = $fullBaseUrl . 'geom/' . urlencode($this->path->id) . '.kml';
                       printf('<a href="%s" title="%s">%s</a>',
                                        $href,
                                        $this->translate('kml export'),
                                        $this->translate('kml export'));

                        print '<br>';
                       $href = $fullBaseUrl . 'geom/' . urlencode($this->path->id) . '.gpx';
                       printf('<a href="%s" title="%s">%s</a>',
                                        $href,
                                        $this->translate('gpx export'),
                                        $this->translate('gpx export'));
                       ?>


                </div>
            </div>
        </div>
    <?php }?>

    <div id="data_controls">
        <div id="data_controls_btns">

    <?php if (isset($this->path)) { ?>
        <input id="clone-btn" name="clone-btn" type="button" value="<?php echo $this->translate('duplicate');?>">
        <br>
        <input id="edit-btn" name="edit-btn" type="button" value="<?php echo $this->translate('edit');?>">
    <?php } else {?>

        <form id="nominatim-form" action="nominatim" method="get">
            <div><a id="nominatim-label" href=""><?php echo $this->translate('Search a place')?></a></div>
            <div id="nominatim-message" class="message"></div>
            <div id="nominatim-controls">
            <input name="nominatim-search" id="nominatim-search">
            <input type="submit" id="nominatim-submit" name="nominatim-submit" value="<?php echo $this->translate('Ok')?>">
            <img id="nominatim-throbber" src="icons/throbber.gif">
            </div>

        </form>

        <input id="create-btn" name="create-btn" type="button" value="<?php echo $this->translate('start a route');?>">
    <?php } ?>
        </div>

    <?php
        print $this->geomform;
    ?>

</div>

<?php if (!isset($this->path)) {?>
            <div id="nominatim-suggestions">
            <div id="nominatim-suggestions-title"><?php echo $this->translate('more results')?></div>
            <ul id="nominatim-suggestions-list"></ul>
            </div>
<?php }?>


</div>

<div id="newpwd_area" class="modal">
    <div id="newpwd_message" class="message"></div>
    <?php
        print $this->newpwdform;
    ?>
</div>

<div id="user_area" class="modal">
    <div id="user_message" class="message"></div>
    <?php
        print $this->userform;
    ?>
</div>

<div id="login_area" class="modal">
   <div id="login_message" class="message"></div>

<?php
  print $this->loginform;
?>

<p id="login_area_create"><a id="login_area_create_anchor" href=""><?php echo $this->translate('create an account')?></a></p>

</div>

<div id="termsofusearea" class="modal">
  <iframe id="termsofuseiframe" width="100%" height="100%" frameborder="0"></iframe>
</div>
