<?php echo $this->localeSwitcher(); ?>
<p><?php
echo $this->translate('Show Your Journey is a site whose goal is to allow anyone to publish routes, for example, hiking itinerary, bicycle trip, travel itinerary or whatever.');
?></p>

<p><?php
echo $this->translate('In order to publish a route, you must first create an account. A valid email is asked for, and ip address of account creation is stored on the server. Those informations will not be divulged to anyone without the user explicit permission.');
?></p>

<p><?php
echo $this->translate('When you create a route, you accept that it\'s free for any use. This means you accept that anyone can reuse, reproduce, or republish your itinerary, or a modified version of it for any purpose. This also means you need to get appropriate permissions from the creator if you want to upload a route you didn\'t create yourself.');
?></p>

<p><?php
echo $this->translate('Show Your Journey is not responsible for the accuracy of the routes published. It\'s the user responsibility to check that a route is accessible and safe.');
?></p>

<p><?php
echo $this->translate('Show Your Journey service is provided "as is" with no guarantee for accuracy or accessibility.');
?></p>

<p><?php
echo $this->translate('Sources of the software running the website are <a href="http://dev.renevier.net/?p=syj.git">publicly available</a> under a agpl license. The map used to display the routes comes from <a href="http://www.openstreetmap.org/">openstreetmap</a>.');
?></p>

