<?php
echo '<div id="footer">' . PHP_EOL;
echo '<div id="footer-padding"></div>' . PHP_EOL;

/*
 * main page link
 */

$front = Zend_Controller_Front::getInstance();
$reqParams = $front->getRequest()->getParams();
if ($reqParams['controller'] == 'idx' and (!isset($reqParams['url']))) {
    $mainpage = true;
} else {
    $mainpage = false;
}

$content = $this->translate("create a route");
$link = ($mainpage) ? $this->escape($content) : $this->anchor($this->baseUrl(), $content, array('class' => 'footer-anchor'));
echo '<div class="footer-link">' . $link . '</div>' . PHP_EOL;

/*
 * contact page link
 */
echo $this->footerLink(array(
        'action'     => 'index',
        'controller' => 'contact',
        'route' => 'contact'),
    $this->translate("contact"),
    isset($this->redirectLinks) ? $this->redirectLinks : true);

/*
 * account link
 */
if ($mainpage or $this->loggedUser) {
    echo $this->footerLink(array(
            'route' => 'account',
            'action'     => 'index',
            'controller' => 'account'),
        $this->translate("my account"), true,
        'logged-show logged-pseudo',
        $this->loggedUser ?  " ({$this->loggedUser->pseudo})": " (%s)"
        );
}

/*
 * list link
 */
if ($mainpage or $this->loggedUser) {
    echo $this->footerLink(array(
            'route' => 'list',
            'action'     => 'index',
            'controller' => 'list'),
        $this->translate("my routes"), false,
        'logged-show');
}

/*
 * login or logout links
 */
if (!$mainpage) {
    if ($this->loggedUser) {

        echo $this->footerLink(array(
            'route' => 'logout',
            'action'     => 'logout',
            'controller' => 'login'),
        $this->translate("logout"),
        false);
    } else {
        echo $this->footerLink(array(
            'route' => 'login',
            'action'     => 'login',
            'controller' => 'login'),
        $this->translate("login"),
        isset($this->redirectLinks) ? $this->redirectLinks : true
        );
    }
}

/*
 * termsofuse
 */
echo $this->footerLink(array(
    'route' => 'termsofuse',
    'action'     => 'index',
    'controller' => 'termsofuse'),
    $this->translate("terms of use"),
    false);

echo '</div>' . PHP_EOL;

?>
